ocaml/ocaml-re

lib/re.ml, lib/re.mli, lib_test/test_easy.ml
=> Replace string

lib_test/test_pcre.ml, lib_test/test_re.ml
=> lib_test: restore compatibility with OCaml pre-4.01

lib/re.ml, lib/re.mli
I fail to see how neither @c-cube nor @rgrinberg added that already. :D
=> Add `exec_opt`, which is similar to exec, but returns an option.

lib/re.mli, lib/re_pcre.mli
Should fix #67 and #70
@dsheets ?
=> Documentation improvements.

lib/re_glob.ml, lib_test/test_exec_iter.ml
Hopefully this restores compatibility with ocaml <= 4.00
=> Remove usage of |>

CHANGES
=> Fix typo in CHANGES

lib/re_glob.mli
=> Fix ocamldoc in re_glob

lib/re_fmt.ml
=> Fix bug in Re.pp

lib/re.ml, lib/re.mli
Pretty print groups in with re
@Drup @c-cube
=> add Re.Group.pp

lib/re.ml
@Drup Only the last commit matters. There's also some indentation corrections that snuck through from ocp-indent.
=> Labelize match str

lib/re.ml, lib/re_automata.ml, lib/re_automata.mli, lib/re_cset.ml, lib/re_cset.mli
Simple re-organizations. Trivially correct. Appear to have no performance
impact.
=> Re_automata cleanups

lib/re_str.ml, lib_test/test_str.ml
@Drup please review (only last commit)
cc @vouillon
Fix #90
=> Fix Re_str splitting

benchmarks/benchmark.ml, benchmarks/http-requests.txt
Two variants are done here:
* Groups of various http sub parts are recognized
* No groups are recognized. Only testing whether an HTTP request is
valid.
@Drup not a completely faithful translation of your tyre version but close
enough. The factor between groups and no groups is quite large as well.
=> Benchmark HTTP request parsing

lib/re.ml
Some cosmetic fix + another fix that should improve compilation speed.
It's not something we have measurements for now, but it can't hurt.
@Drup
=> Tiny improvements

lib/re.ml
=> Document fields of group type

lib/re.ml
* Some style changes
* Share code between `Group.get` and `Group.offset`
* Fix nb_count
=> Group improvements

lib/re_automata.ml, lib/re_cset.ml
=> Remove unused "used" parameter

benchmarks/benchmark.ml
Re.re caches various things, so it's best not to reuse the re
between different benchmarks
=> Improve benchmarks

lib_test/test_str.ml
Only passing tests are running for now. Will enable the failing tests once the bugs are fixed.
=> Add tests for Re_str.global_replace

lib/re_fmt.ml, lib/re_str.ml, lib_test/test_str.ml
Make all functions in Re_str tail recursive (like they are in Str). Also add proper tests for every function.
=> Improve Re_str tail recursion/tests

lib_test/test_str.ml
Make global_replace like the split tests in this module. Also remove pointless local opens.
=> Slight improvement to Re_str tests

lib/re_str.ml
`mtch` and `srch` fields are just manually implemented lazy fields. It's
a bit cleaner to simply use the lazy module.
=> Use explicit laziness in Re_str

lib/re_str.ml
`{end,beginning}_group` aren't very useful. offset_group is a lot more
useful. `get_len` is also renamed to `group_len`
=> Simplify Re_str internals

lib/automata.ml, lib/automata.mli, lib/category.ml, lib/category.mli, lib/core.ml, lib/pmark.ml, lib/pmark.mli
These can now live in their modules.
=> Mark * Category cleanup

lib/core.ml, lib/core.mli, lib/jbuild, re.opam
Functional iterators are the future!
cc @Drup 
close #158
=> feat: add `Seq`-based iterators

lib/core.ml, lib_test/test_re.ml
@dwang20151005 This addresses all of your examples but introduces weird behavior with the 3rd example. I'm not sure why it's Partial and not Full (perhaps @vouillon 
knows?).
Leaving this to @Drup to review as I believe he introduced this in 1.5.0
=> Fix Re.exec_partial regression

.travis.yml, dune-workspace.dev, lib/fmt.ml, lib_test/test_easy.ml, re.opam
This requires bumping the minimum required version to OCaml 4.03
=> Add support for OCaml 5.00 to the tests

lib/color_map.ml, lib/color_map.mli, lib/core.ml, lib/group.ml
- simplify the main loop
- use strings rather than bytes for immutable byte arrays
=> Some cleanup

.vscode/settings.json
=> remove .vscode settings

dune, lib_test/fort_unit/dune
=> chore: dune file formatting

lib/automata.mli
=> refactor: remove [Automata.Marks] from interface

Makefile
=> chore: remove old nix cruft

lib/core.mli
=> doc: fix typo

lib/core.mli
=> doc: replace [Re.substrings] with [Re.Group.t]

lib_test/test_perl.ml
=> test: remove some pointless indentation

lib_test/dune, lib_test/test_posix.ml
Re.Posix doesn't support character classes
=> test: reproduce #213

lib/automata.ml, lib/automata.mli, lib/core.ml
=> refactor: make [Automata.State] abstract

lib/perl.ml
=> refactor(perl): raise [Exit] without backtrace

lib/automata.ml
=> refactor: factor our common expression

lib/automata.ml, lib/automata.mli
=> refactor: remove some unused things from [Automata] interface

lib/automata.ml
=> refactor: move helpers to scope of [prepend_marks]

lib/automata.ml, lib/automata.mli, lib/core.ml
=> refactor: move [Automata.status] to [Automata.State]

lib/automata.ml
=> refactor: move inline marks_set_idx helper

lib/emacs.ml, lib/parse_buffer.ml, lib/parse_buffer.mli, lib/perl.ml, lib/posix.ml
In particular, share the basic building block for tracking our position within the parsed string and looking for specific chars.
=> refactor: share some pcre parser bits

benchmarks/benchmark.ml
=> bench: fix string traversal benchmark

benchmarks/benchmark.ml
=> bench: remove manual repetition

lib/automata.ml, lib/automata.mli, lib/group.ml, lib/group.mli, lib/mark_infos.ml, lib/mark_infos.mli
Allows us to hide its mutability
=> refactor: move mark_infos to separate module

lib/core.ml
A very nice performance improvement
=> Rebase #210

lib/automata.ml
=> refactor: Add [Marks.set_{p,}mark]

lib/automata.ml
=> refactor: [is_tmatch]

lib/perl.ml, lib/posix.ml
=> refactor: factor some common expressions in parsers

lib/automata.ml, lib/core.ml
* reduce the scopes of identifiers
* share some common expressions
=> refactor: some general cleanups

lib/core.ml
=> refactor: simplify handle_last_newline

lib/automata.ml
=> refactor: move [prev_cat] closer to use

lib/core.ml
=> refactor: add label to int arg

lib/automata.ml
=> refactor: remove unnecessary module qualification

lib/automata.ml
=> refactor: remove unnecessary qualification

lib_test/test_glob.ml
=> test: more double glob star parsing

lib/automata.ml
=> refactor: move state description to submodule

lib/core.ml
=> refactor: share some [State.get_info st] calls

lib/glob.ml
Use Parse_buffer's api for parsing strings
=> refactor: use [Parse_buffer] in glob parser

benchmarks/memory.ml
Include another pathological case
=> chore: improve memory benchmarks

lib/ast.ml, lib/core.ml, lib/import.ml
* remove some pointless prime suffixes
* add some trivial helpers to simplify case conversion
=> refactor: use [ListLabels]

lib/core.ml
To avoid having to pass them everywhere
=> refactor: move compilation params to record

lib/ast.ml
one [seq] should be enough for everyone
=> refactor: remove duplicate definition

lib/ast.ml, lib/core.ml
It has nothing to do with the ast
=> refactor: move trans_set to core

lib/core.ml
these constructors are eliminated by handle_case
=> refactor: witness should assert false for more constructors

lib/ast.mli
Makes it possible to enforce various internal invariants of [Ast.t] construction
=> refactor: add mli to [Ast]

lib/ast.ml, lib/ast.mli, lib/core.ml
Allows us to eliminate a bunch of assert false
=> refactor: make ast generic over the cset

lib/ast.ml, lib/ast.mli, lib/core.ml
allows us to get rid of a few more assert falses
=> refactor: add caseless ast

lib/ast.ml, lib/ast.mli, lib/core.ml, lib/core.mli, lib/re.ml, lib/replace.ml, lib/replace.mli, lib/search.ml
=> refactor: move replace/search to own modules

lib/ast.ml, lib/ast.mli, lib/compile.ml, lib/view.ml
Remove sem/sem_greedy from cset ast
=> refactor: simplify ast

lib/automata.ml
* no more polymorphic comparison
* use labels
=> refactor: clean up automata handling

lib/automata.ml
simplifies passing around a bunch of stuff
=> refactor: move char, categories to context record

lib/str.ml
narrow the try/catch to the the parts that are necessary
=> refactor(str): improve exception handling

dune-project, lib/compile.ml, lib/compile.mli, lib_test/expect/dune, lib_test/expect/import.ml, lib_test/expect/test_validation.ml, lib_test/unit/test_perl.ml, re.opam
unfortunately, it's impossible b/c ppx_expect itself uses re
=> test: use ppx_expect

lib/automata.ml
This helps with the pathological benchmark/memory.ml bench
=> refactor: replace list with hash table for de-duplication

benchmarks/memory.ml
re-create the re for every test
=> refactor: improve memory benchmark

lib/pcre.mli
See https://github.com/ocaml/ocaml-re/issues/295
=> Add a mention of the state of PCRE support in its interface file

lib/compile.ml
Saves one word of memory without any observable performance penalty.
Could probably be written without multiplication if anyone's interested.
=> refactor: remove real_idx

CHANGES.md, lib/core.mli, lib/group.ml, lib/group.mli
=> feature: add non raising versions of all group functions

lib/compile.ml
doesn't make the code cleaner nor faster
=> refactor: remove [pos] from info

lib/compile.ml
gives another speed improvement
=> refactor: remove last from info record

lib/compile.ml
removes the allocation of a record for [execp]
=> refactor: get rid of info record altogether

lib/automata.ml, lib/import.ml
=> refactor: use unboxed option for status

lib/automata.ml
=> refactor: improve set_idx a little

lib/automata.ml, lib/import.ml
they crash on flambda for some reason
=> fix: remove unboxed options

.github/workflows/nix.yml, flake.nix
dev deps aren't needed to run tests
=> chore(nix): stop installing everything in CI

lib/automata.ml
the conversion to dyn is good enough
=> refactor: remove pretty printer hackery
