lib/re.ml
lib/re.mli
lib/re_automata.ml
lib/re_automata.mli
lib_test/fort_unit.ml
lib_test/test_re.ml

Path marks allow to mark a specific regexp and receive a mark
identifier. Once you have matched the regexp, you can know if the marked
regexp was used.
There is a bit of clean up first to turn some structural typing into actual typing. It makes the editing much simpler.

Add path marks.

---

lib/re.ml
lib/re.mli
lib/re_pcre.ml
lib/re_pcre.mli
lib/re_str.ml
lib_test/re_match.ml
lib_test/test_easy.ml
lib_test/test_re.ml
lib_test/test_str.ml

As discussed in #43
I though that "Group" was a better name (consider Group.get, Group.all, Group.test). I'm sure we will bikeshed the names thoroughly, though. :)
I also added the Mark module.
I'll probably drop the commit with the deprecation warnings, but it was nice to have them.

Add the Group and Mark modules

---

lib/re_glob.ml
lib/re_glob.mli
lib_test/test_glob.ml

The glob API now exposes a single function with multiple optional arguments, rather than having several similarly-named functions with slightly different functionality.

Prefer optional arguments instead of multiple glob functions

---

lib_test/re_match.ml
lib_test/test_str.ml

* Remove seemingly pointless `String.copy`
* prefix unused variable with `_`
* Remove frivolous use of `and`. No need to use this without a recursive
binding.

Fix last remaining warnings

---

.travis-ci.sh
lib/re_glob.ml
lib/re_glob.mli
lib_test/glob.ml
lib_test/test_glob.ml

Separate glob parsing from translation to the RE type.
Make the glob translation code a more obvious state machine.
This is a rewrite of all the glob code. The goal is to make the statefulness more explicit, make the parsing and translation phases distinct, and make the code more straightforward for new changes.

Rewrite glob code, with support for not explicitly matching slashes.

---

.travis.yml
lib/re.ml

Bring back 4.00 compatibility

---

lib/re.ml

execp and exec_partial return either a flag or a boolean without any
group information. There's no need to initialize the group then.
Fix #105 
cc @Drup @sliquister @vouillon

exec{p,_partial} shouldn't initialize groups

---

lib/re.ml

tbl, pos, and last are all fields that are mutable but don't have to be.
Only last actually gets mutated, and we can easily replace it with a
functional update.
Benchmarks show this is just noise:
```
Name                             | Time(master) | Time(remove-mutability) | Delta   |
---------------------------------------------------------------------------------------
| 20 zeroes/exec/case 0            | 174.60ns     | 179.85ns | 3.01%   |
| 20 zeroes/execp/case 0           | 156.43ns     | 137.40ns | -12.17% |
| 20 zeroes/exec_opt/case 0        | 178.79ns     | 186.61ns | 4.37%   |
| lots of a's/exec/case 0          | 447.39ns     | 445.98ns | -0.32%  |
| lots of a's/execp/case 0         | 466.45ns     | 469.01ns | 0.55%   |
| lots of a's/exec_opt/case 0      | 447.45ns     | …
```

Remove unnecessary mutability

---

lib_test/test_easy.ml

lookaround assertions like {b,e}o{l,w,s} don't have any width and so are
always present in the result of split. We should at least test this
slightly unintuitive behavior

Add tests for split with zerowidth re's

---

lib/re.ml
lib/re.mli
lib/re_cset.ml
lib/re_cset.mli
lib_test/test_re.ml

`Re.witness re` is a function that generates a string s
such that `Re.execp (Re.compile re) s = true`
cc @Drup
This is really rough and dirty but I'm just hesitant of including
something like this in re. It seems like a completely useless
function for most users and hence just API bloat.

Implement Re.witness

---

lib/re_str.ml
lib_test/test_str.ml

`orig` and `repl` arguments were accidentally switched for 2 recursive calls. Add regression tests for this issue.
Fix #129
cc @Drup

Fix Re_str.global_replace

---

lib_test/test_str.ml

test_str.global_replace switched the order of the expected and actual
arguments which caused incorrect output when the tests failed.

Fix switched arguments in global_replace test

---

.gitignore
benchmarks/jbuild
jbuild
lib/jbuild
lib_test/jbuild

* Set jbuild_version in a single file
* Update dependencies to include bytes
* Don't wrap Re module (for backwards compat.)
* Add build rules for tests
* Add build rules for benchmarks
* Update .gitignore to include .merlin and .install. These will be generated
by jbuilder

Update jbuilder rules

---

lib/jbuild
re.opam

Since ocaml-re now required OCaml 4.02.3 or later.
It's a slight nuisance for opam's vendored build, since by default it's built without `ocamlfind` present.

Remove dependency on bytes package

---

lib/perl.mli

Two comments in lib/perl.mli was switch. This PR correct it.

Correct doc string in perl.mli

---

lib/perl.ml
lib_test/test_perl.ml

I hit this one:
```
utop # Re.Perl.re {|[\|};;
Exception: Invalid_argument "index out of bounds".
```

Fix index-out-of-bounds for Re.Perl.re {|[\|}.

---

lib/perl.ml
lib_test/test_perl.ml

I found two more issues in the `Re.Perl` parser:
- `(?#` gave index out of bounds, changed to parse error.
- The backslash item in `[a-\sz]` terminated the `[` due to missing recursive call to `bracket`.

Two fixes for Re.Perl parser

---

lib/core.ml
lib/core.mli

Exposes the variant type [t] for pattern matching by downstream users, without allowing unchecked construction.

Expose view of regex type

---

CHANGES.md
lib/color_map.ml
lib/color_map.mli
lib/core.ml
lib/core.mli
lib/glob.ml
lib/group.ml
lib/group.mli
lib/pcre.ml
lib/pcre.mli
lib_test/test_easy.ml
lib_test/test_re.ml
re.opam

The biggest change is the move of the gen/seq/list modules to their own sub modules. This has a couple of advantages (plus I like names without suffixes more):
* We'll be able to enforce that they all have the same interfaces via module types (I'll do that later).
* Once we re-organize the library a little more, we'll be able to have these unused functions removed by the dead code elimination.
I've also moved a few other chunks of code to their own modules. `core.ml` is getting quite heavy, so I think it's a step in the right direction.
The added comments + better names are self explanatory I think.

Some cleanup + More consistent naming

---

CHANGES.md
lib/perl.ml

This seems to be the only one missing compared to the list in `man perlrecharclass`.

Support POSIX `[:alpha:]` character class

---

CHANGES.md
lib/glob.ml
lib/glob.mli
lib_test/test_glob.ml

Hi,
This PR adds support for double asterisks (`**`) to `Glob`.
It is like `*` but also matches `/` characters, even when `pathname` is set.
For example, `foo/**` will match both `foo/bar` and `foo/bar/baz`.
The `period` flag still work, `foo/**` won't match `foo/.bar` but `foo/.**` will.
Related to issue https://github.com/ocaml/ocaml-re/issues/171
This is useful in OCamlformat, where the matching is done on the whole path: https://github.com/ocaml-ppx/ocamlformat/issues/1234

Glob: Double asterisk match including slash

---

benchmarks/.merlin
benchmarks/benchmark.ml

In a near future `.merlin` files won't be promoted to sources by dune anymore. This break the build of projects using dune with hard-coded `.merlin` files in their sources.
This PR removes the (useless since the project moved to dune) file `benchmarks/ .merlin`.
I also took the opportunity to correct the benchmark code that was not up-to-date with some api changes of `Core` and `Re` itself.
<details><summary>Useless bonus: results under WSL, core i7 8700 and 16go ram</summary><p>
```
{{Estimated testing time 4m (24 benchmarks x 10s). Change using '-quota'.
┌──────────────────────────────────┬──────────────┬────────────┬──────────┬──────────┬────────────┐
│ Name                             │     Time/Run │    mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │ …
```

Remove dot `.merlin` (and fix benchmark)

---

lib/automata.ml

Otherwise things usually get printed mostly horizontally and squished
against the max formatter width.

More line breaks in the pp functions

---

lib/core.mli
lib/group.ml
lib/group.mli
lib_test/fort_unit/fort_unit.ml
lib_test/test_re.ml

A lot of the api in core.mli has barely any documentation, and the behavior is not obvious at all. Or sometimes, the behavior is the expected one, but since it's not documented, you end up having to test it to make sure. So this is trying to address that.
The first commit adds `Re.Group.get_opt` because it sounds like a straightforward omission, and I wanted it for an example in the documentation. The second commit is pure documentation. I think the documentation I wrote is correct, and I tested some of it, but I am not 100% sure.
I wanted to add something about marks, but I didn't, because I don't see the point of using them over using an empty group (performance maybe? or is just simpler api? or do they simply because they are used internally so it's easy to provide?).

More documentation

---

lib/str.ml

Commit 88868e1 did not actually make `global_substitute` tail recursive (I haven't verified the others) because `try...with` prevents tail call optimization. Switching to matching on the exception fixes this and prevents stack overflow errors.

Make global_substitute tail recursive

---

lib/str.mli

Greetings,
Today, I was looking for documentation for the `Re.Str.regexp_string` function [here](https://docs.ocaml.pro/html/LIBRARY.re_str@re.1.9.0/Re_str/index.html#val-regexp_string) and it took me a moment to realize that its usage was defined under the `Re.Str.regexp_string_case_fold` function right beneath it.
After looking deeper into the `str.mli` file, I've noticed similar pratices for other closely related functions and proceeded to separate all usages to make it clearer to the newer reader.
To me, this seemed like a slight oversight, especially in regards to opam package documentation generation tools, that required very minimal effort to correct, so hopefully you'll find it non-trivial enough to merge it.
Finally, this is my first contribution to any ocaml repository, please …

[DOC] separate doc comments in str.mli for closely related functions

---

CHANGES.md
lib/glob.ml
lib_test/test_glob.ml

Fixes #185 
I don't know, if this is a good implementation for the fix (I rather doubt it) but maybe it can be used as a starting point to further improve on.
As I already noted in the issue, the problem was, that the parser saw the `/`'s as explicitly set characters that needed to be present.
I am now checking, if the double asterisk has leading or trailing slashes and ignore them if there are any.
If the trailing slash is in the last place, I do _not_ ignore it, so the test on [line 94](https://github.com/eWert-Online/ocaml-re/blob/690a002571be79190c8362b4b48b8348bf99d7ab/lib_test/test_glob.ml#L94) does not fail.
If you have any suggestions for an implementation that is easier to understand / read, I would be happy to hear it 😄

Glob: Make double asterisk match zero or more directories

---

CHANGES.md
lib/glob.ml
lib/glob.mli
lib_test/test_glob.ml

After sleeping on it a few days I realized that the API in #198 was not optimal as it removed the ability to escape characters in the glob pattern if one wanted to pattern match paths with backslashes. This PR proposes a small tweak: the new argument to `glob` activates a mode where a forward slash will also match a backslash, but a backslash on the pattern itself will continue to escape the following character.
Apologies for the back-and-forth, but I thought it is preferable to get the API right before doing a release with the new functionality!

Tweak 'backslash' API

---

CHANGES.md
lib/core.ml
lib_test/test_re.ml

In addition to the minimal fix suggested by Vouillon in #146, this PR
allows `Category.inexistant` characters (i.e., `bos` and `eos`) in the
following places:
1. before `bow`
2. after `eow`
3. on both sides of `not_boundary` (but not one side alone)
That minimal fix would still give an unintuitive and unconventional
interpretation of word boundaries where `bos` and `eos`...
1. are accepted on both sides of a word boundary (`bow` or `eow`)
2. are not accepted on either side of a `not_boundary`
With the minimal fix, `bow` and `eow` matches would not need to have a
word between them. E.g.,
1. in `""`, both `bow` and `eow` would match at position 0 with
nothing between them
2. in `"#"`, `bow` would match before the `#` and `eow` after the `#`,
even though `#` is not a word character.
In …

Improve handling of word boundaries, fix #146

---

lib/posix.mli

I haven't figured out how to get dune+odoc to render the [main module comment on ocaml.org](https://ocaml.org/p/re/1.10.3/doc/Re_posix/index.html) correctly though.
However compile and compile_pat's documentation were swapped, and it is best to document which syntax compile_pat uses, to make it clear it uses the extended syntax.
The long comment at the bottom about differences vs the standard should also be rendered in the documentation somehow...

Re.Posix: fix documentation

---

CHANGES.md
lib/core.ml
lib/core.mli

I'm programming a PPX rewriter based on `re`.  In this, I'd like the regexp `a(b?)c` to result in a function of type
`string -> (string * string option) option`: that is, two capture groups.  So I'd like to be able to query the compiled regexp for the # of capture groups before executing it.

a trivial little extension to allow querying group_count

---

re.opam

Changed it so it mentions 2.1 instead of 2.0 and it now follows the SPX format for licenses.
The opam repository should be changed as well, this affects alls versions of the library AFAIK

Use correct AGPL version in opam metadata

---

CHANGES.md
lib/core.ml
lib/core.mli
lib_test/test_re.ml

This is similar to `exec_partial`, but it allows users to see the groups that matched if a match exists, and if not, then it tells you an index before which a match cannot start.
We had some code that was searching for a relatively small snippet within a large collection of text using regexes. This collection of text arrived in chunks, and the snippet could lie within the boundary of the chunks. We would only stop consuming chunks if we found the snippet. The most generic solution was to keep appending the chunks to a buffer, and redo the regex search from the beginning. However, that lead to $O(n^2)$ performance around larger inputs, and was resulting in significant slowdowns. Using this method, we could start the search at a later index, resulting in effectively $O(n)$ improvement.
We …

Add an [exec_partial_detailed] function to re.

---

lib/automata.ml

inline [first] on [TMatch]

---

lib/automata.ml

refactor: rename [delta_2] to [delta_alt]

---

benchmarks/benchmark.ml
benchmarks/dune
benchmarks/memory.ml

`$ dune exec benchmarks/memory.exe` will demonstrate the pathological example

bench: add memory benchmarks

---

dune-project
lib_test/dune
lib_test/fort_unit/dune

chore: turn off implicit transitive deps

---

CHANGES.md
lib/perl.ml
lib/posix.ml
lib/posix_class.ml
lib/posix_class.mli
lib_test/test_posix.ml

feature: support posix classes in Re.Posix

---

lib/core.ml

refactor: remove a couple of extra state info accesses

---

lib/core.ml

[Repeat (_, 0, Some 0)] = empty
[Repeat (r, 1, Some 0)] = r

fix: simplify [Repeat]

---

lib/core.ml
lib/fmt.mli
lib/group.ml

refactor: add mli to our fmt module

---

lib/core.mli

Adds a few examples of using zero-length patterns as inputs to Re.split.  Examples are taken from the test suite.  Related to #119 and #120.
I know it is an old issues (this one: https://github.com/ocaml/ocaml-re/issues/119), but I also tried to use the `eol` as input for `split` in the past.  So, I took a couple of the test cases and added them to the examples for `Re.split`.

Add examples for Re.split function

---

lib/ast.ml

Intersection/Complement/Difference are only defined on character sets anyway. There's no need to check again.

refactor: remove pointless [is_charset] checks

---

lib/ast.ml
lib/core.ml

is_charset was quadratic. This is fixed by maintaining what's a character set at AST construction time rather than compilation. As a bonus, this also means that the checks are are completely reused between different `Re.compile` calls.

fix: quadratic compilation complexity

---

lib/ast.ml
lib/ast.mli
lib/core.ml

To make it impossible to construct ast's without respecting the invariants

refactor: make the types in Ast private

---

lib/compile.ml
lib/compile.mli
lib/core.ml

there's no need to allocate the match record only to immediately throw it away in [execp]

refactor: speed up [execp]

---

lib/compile.ml

chore: remove mention of old field

---

CHANGES.md
lib/compile.ml
lib/compile.mli
lib/core.ml
lib/core.mli
lib/slice.ml
lib/slice.mli
lib_test/expect/dune
lib_test/expect/test_stream.ml

feature: add streaming interface

---

lib/pcre.ml
lib_test/expect/test_pcre_288.ml
lib_test/expect/test_pcre_split.ml

An occurrence of the delimiter at the beginning or at the end of the string is ignored.
Fixes #288, fixes #411.

Fix Pcre.split

---

lib/emacs.ml
lib_test/str/test_str.ml

Backward ranges like `[5-4]` were treated incorrectly

Fix handling in Re.{Emacs,Str}

---

lib/emacs.ml
lib/perl.ml
lib/posix.ml
lib_test/expect/test_alternation.ml

When compiling [(a|b|c)], we used to parse it as:
Re.alt [ x ; Re.alt [ y ; z ] ]
Now, we just flatten the alternation:
Re.alt [ x ; y ; z ]

refactor: do not nest alternations

---

dune-project
lib/dune
lib_test/expect/dune
re.opam

seq has been included in the OCaml stdlib since 4.07, and re's lower bound is already >=4.12.0

Remove explicit seq dependency

---

lib/pcre.ml
lib_test/expect/test_pcre_split.ml

Always return results from Pcre.split in the right order

---

lib/import.ml

The ocaml compiler (without flambda) does not optimize `Int.compare x y = 1` into a plain comparison.

Generate simpler code for comparisons

---

dune-project
lib/emacs.ml
lib/fake/atomic.ml
lib/import.ml
re.opam

Disclaimer: this is totally fine if this PR isn't merged.
I'm trying to upgrade to re 1.14.0 in opam itself and i was faced by the new lower-bound restriction on OCaml 4.13.
I needed to make a patch for us to be able to use it and i'm sharing it here in case anyone else faces the same issue.
I've split the commits in two as given the opam file expected OCaml >= 4.12 to work, i'm guessing dropping 4.12 wasn't intended.
The second commit backports to OCaml 4.08 with an implementation of atomics similar to the one added in OCaml 4.12: https://github.com/ocaml/ocaml/commit/04d9c425f38e892232078b7f56a1d323dcf8ba00
Feel free to take or drop any one of these commits

Backport re to OCaml 4.08
